#!/usr/bin/env python3
"""Copy approved manifest candidates into knowledge_inbox with normalized names.

Reads data/mep_rag/ingestion_manifest.json generated by prepare_sbc_manifest.py.
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "data" / "mep_rag" / "ingestion_manifest.json"
INBOX = ROOT / "knowledge_inbox"


def _safe_token(text: str) -> str:
    token = "".join(ch if ch.isalnum() else "-" for ch in text.strip())
    token = "-".join(part for part in token.split("-") if part)
    return token[:80] if token else "unknown"


def _load_manifest() -> list[dict]:
    if not MANIFEST.exists():
        raise FileNotFoundError(f"Manifest not found: {MANIFEST}")

    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    return list(data.get("candidates") or [])


def _build_target_name(item: dict, source_path: Path) -> str:
    code_family = _safe_token(str(item.get("code_family", "SBC")))
    code_number = _safe_token(str(item.get("code_number", "")))
    edition = _safe_token(str(item.get("edition", "TBD")))
    source_id = _safe_token(str(item.get("source_id", "source")))
    return f"{code_family}-{code_number}_{edition}_{source_id}{source_path.suffix.lower()}"


def main() -> int:
    parser = argparse.ArgumentParser(description="Stage approved SBC files into knowledge_inbox")
    parser.add_argument("--dry-run", action="store_true", help="Preview without copying")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite target files if they exist")
    args = parser.parse_args()

    candidates = _load_manifest()
    INBOX.mkdir(parents=True, exist_ok=True)

    copied = 0
    skipped = 0

    for item in candidates:
        src = Path(str(item.get("local_file_path", "")))
        if not src.exists() or not src.is_file():
            skipped += 1
            print(f"SKIP missing source: {src}")
            continue

        target_name = _build_target_name(item, src)
        dst = INBOX / target_name

        if dst.exists() and not args.overwrite:
            skipped += 1
            print(f"SKIP exists: {dst}")
            continue

        if args.dry_run:
            print(f"PLAN copy: {src} -> {dst}")
            copied += 1
            continue

        shutil.copy2(src, dst)
        copied += 1
        print(f"COPIED: {dst}")

    mode = "DRY-RUN" if args.dry_run else "EXECUTE"
    print(f"Mode: {mode}")
    print(f"Candidates: {len(candidates)} | Prepared/Copied: {copied} | Skipped: {skipped}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
